In [6]:
# Numpy
import numpy as np
import sys

s=range(1000)
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of whole list in bytes:",sys.getsizeof(s)*len(s))

d=np.arange(1000)
print("Size of each element in numpy arrays in bytes:",d.itemsize)
print("Size of whole numpy arange in bytes:",d.itemsize*d.size)

Size of each element of list in bytes: 48
Size of whole list in bytes: 48000
Size of each element in numpy arrays in bytes: 4
Size of whole numpy arange in bytes: 4000


In [25]:
import numpy as np
arr2=np.array(42)
print(arr2)
print(arr2.ndim)
print(type(arr2))

arr3=np.array([1,2,3,4])
print(arr3)
print(arr3.ndim)
print(type(arr3))

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
print(type(arr))

arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.ndim)
print(type(arr1))

arr4=np.array([[[1,2,3]]])
print(arr4)
print(arr4.ndim)
print(type(arr4))

42
0
<class 'numpy.ndarray'>
[1 2 3 4]
1
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
2
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
<class 'numpy.ndarray'>
[[[1 2 3]]]
3
<class 'numpy.ndarray'>


In [31]:
# Shape
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[6,7,8,9]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr4=np.array([[1,2],[1,2],[1,2],[1,2]])

print(arr1.ndim)
print(arr1.shape)

print(arr2.ndim)
print(arr2.shape)

print(arr3.ndim)
print(arr3.shape)

print(arr4.ndim)
print(arr4.shape)

1
(5,)
2
(2, 4)
3
(2, 2, 3)
2
(4, 2)


In [34]:
import numpy as np

arr=np.array([1,2,3,4,5],ndmin=5)
print(arr.ndim)
print(arr.shape)

5
(1, 1, 1, 1, 5)


In [39]:
# Reshape
import numpy as np
# arr1=np.array([1,2,3,4,5])   Error
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,3)
print(newarr)
print()
newarr=arr1.reshape(3,2)
print(newarr)
print()
newarr=arr1.reshape(2,-1) # -1 will calculate it by its own
print(newarr)
print()
newarr=arr1.reshape(2,-1).base
print(newarr)
print()

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]



In [55]:
# Reshape
import numpy as np

arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
for x in arr:
    for y in x:
        print(y)
print()

for x in np.nditer(arr):
    print(x)
print()
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
2
3
4
5
1
2
3
4
5

1
2
3
4
5
1
2
3
4
5

1
3
5


In [66]:
# concatenate
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)

arr4=np.array([[1,2],[3,4]])
arr5=np.array([[5,6],[7,8]])
arr6=np.concatenate((arr4,arr5))
print(arr6)
arr6=np.concatenate((arr4,arr5),axis=0)
print(arr6)
arr6=np.concatenate((arr4,arr5),axis=1)
print(arr6)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [82]:
# Split

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,4)
print(newarr)

arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr1=np.array_split(arr1,4,axis=1)
print(newarr1)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [86]:
# Where

import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4)
print(x)
y=np.where(arr%2==0)
print(y) # its giving index not number.

# Doubt
arr1=np.array([[1,2],[3,4],[4,5],[7,8]])
x=np.where(arr1==4)
print(x)

(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([1, 2], dtype=int64), array([1, 0], dtype=int64))
